/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as ApiActionsRouteImport } from './routes/api.actions'
import { Route as ApiAttachmentsRouteImport } from './routes/api.attachments'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiStateRouteImport } from './routes/api.state'
import { Route as ApiAttachmentsAttachmentIdRouteImport } from './routes/api.attachments.$attachmentId'
import { Route as ApiCopilotkitSplatRouteImport } from './routes/api.copilotkit.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiActionsRoute = ApiActionsRouteImport.update({
  id: '/api/actions',
  path: '/api/actions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsRoute = ApiAttachmentsRouteImport.update({
  id: '/api/attachments',
  path: '/api/attachments',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStateRoute = ApiStateRouteImport.update({
  id: '/api/state',
  path: '/api/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttachmentsAttachmentIdRoute =
  ApiAttachmentsAttachmentIdRouteImport.update({
    id: '/$attachmentId',
    path: '/$attachmentId',
    getParentRoute: () => ApiAttachmentsRoute,
  } as any)
const ApiCopilotkitSplatRoute = ApiCopilotkitSplatRouteImport.update({
  id: '/api/copilotkit/$',
  path: '/api/copilotkit/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/profile': typeof ProfileRoute
  '/today': typeof TodayRoute
  '/trends': typeof TrendsRoute
  '/workout': typeof WorkoutRoute
  '/api/actions': typeof ApiActionsRoute
  '/api/attachments': typeof ApiAttachmentsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/state': typeof ApiStateRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/copilotkit/$': typeof ApiCopilotkitSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/profile': typeof ProfileRoute
  '/today': typeof TodayRoute
  '/trends': typeof TrendsRoute
  '/workout': typeof WorkoutRoute
  '/api/actions': typeof ApiActionsRoute
  '/api/attachments': typeof ApiAttachmentsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/state': typeof ApiStateRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/copilotkit/$': typeof ApiCopilotkitSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent': typeof AgentRoute
  '/profile': typeof ProfileRoute
  '/today': typeof TodayRoute
  '/trends': typeof TrendsRoute
  '/workout': typeof WorkoutRoute
  '/api/actions': typeof ApiActionsRoute
  '/api/attachments': typeof ApiAttachmentsRouteWithChildren
  '/api/chat': typeof ApiChatRoute
  '/api/state': typeof ApiStateRoute
  '/api/attachments/$attachmentId': typeof ApiAttachmentsAttachmentIdRoute
  '/api/copilotkit/$': typeof ApiCopilotkitSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/profile'
    | '/today'
    | '/trends'
    | '/workout'
    | '/api/actions'
    | '/api/attachments'
    | '/api/chat'
    | '/api/state'
    | '/api/attachments/$attachmentId'
    | '/api/copilotkit/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/profile'
    | '/today'
    | '/trends'
    | '/workout'
    | '/api/actions'
    | '/api/attachments'
    | '/api/chat'
    | '/api/state'
    | '/api/attachments/$attachmentId'
    | '/api/copilotkit/$'
  id:
    | '__root__'
    | '/'
    | '/agent'
    | '/profile'
    | '/today'
    | '/trends'
    | '/workout'
    | '/api/actions'
    | '/api/attachments'
    | '/api/chat'
    | '/api/state'
    | '/api/attachments/$attachmentId'
    | '/api/copilotkit/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentRoute: typeof AgentRoute
  ProfileRoute: typeof ProfileRoute
  TodayRoute: typeof TodayRoute
  TrendsRoute: typeof TrendsRoute
  WorkoutRoute: typeof WorkoutRoute
  ApiActionsRoute: typeof ApiActionsRoute
  ApiAttachmentsRoute: typeof ApiAttachmentsRouteWithChildren
  ApiChatRoute: typeof ApiChatRoute
  ApiStateRoute: typeof ApiStateRoute
  ApiCopilotkitSplatRoute: typeof ApiCopilotkitSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/actions': {
      id: '/api/actions'
      path: '/api/actions'
      fullPath: '/api/actions'
      preLoaderRoute: typeof ApiActionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments': {
      id: '/api/attachments'
      path: '/api/attachments'
      fullPath: '/api/attachments'
      preLoaderRoute: typeof ApiAttachmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/state': {
      id: '/api/state'
      path: '/api/state'
      fullPath: '/api/state'
      preLoaderRoute: typeof ApiStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attachments/$attachmentId': {
      id: '/api/attachments/$attachmentId'
      path: '/$attachmentId'
      fullPath: '/api/attachments/$attachmentId'
      preLoaderRoute: typeof ApiAttachmentsAttachmentIdRouteImport
      parentRoute: typeof ApiAttachmentsRoute
    }
    '/api/copilotkit/$': {
      id: '/api/copilotkit/$'
      path: '/api/copilotkit/$'
      fullPath: '/api/copilotkit/$'
      preLoaderRoute: typeof ApiCopilotkitSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiAttachmentsRouteChildren {
  ApiAttachmentsAttachmentIdRoute: typeof ApiAttachmentsAttachmentIdRoute
}

const ApiAttachmentsRouteChildren: ApiAttachmentsRouteChildren = {
  ApiAttachmentsAttachmentIdRoute: ApiAttachmentsAttachmentIdRoute,
}

const ApiAttachmentsRouteWithChildren = ApiAttachmentsRoute._addFileChildren(
  ApiAttachmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentRoute: AgentRoute,
  ProfileRoute: ProfileRoute,
  TodayRoute: TodayRoute,
  TrendsRoute: TrendsRoute,
  WorkoutRoute: WorkoutRoute,
  ApiActionsRoute: ApiActionsRoute,
  ApiAttachmentsRoute: ApiAttachmentsRouteWithChildren,
  ApiChatRoute: ApiChatRoute,
  ApiStateRoute: ApiStateRoute,
  ApiCopilotkitSplatRoute: ApiCopilotkitSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
