import type {Locale} from './contracts'
const errors:Record<string,[string,string]>={
 ATTACHMENT_NOT_FOUND:['This image is no longer available. Attach it again.','这张图片已不可用，请重新上传。'],
 ATTACHMENT_PURPOSE_MISMATCH:['Attach this image again and choose whether it is food or a menu.','请重新上传图片，并选择食物或菜单用途。'],
 INVALID_ATTACHMENT_CONTENT:['This image could not be opened. Choose another JPEG, PNG or WebP file.','无法打开这张图片，请选择另一张 JPEG、PNG 或 WebP 图片。'],
 PROPOSAL_NOT_CREATED:['A plan is not ready to apply. Open Agent to review its reply and add any missing details.','方案暂未准备好，请前往助手查看回复并补充所需信息。'],
 RUN_IN_PROGRESS:['The assistant is still working. Wait for the reply before trying again.','助手仍在处理，请等待回复后再试。'],
 RUN_STOPPED:['The reply was stopped. Saved changes are kept.','回复已停止，已保存的修改会保留。'],
 SEARCH_FAILED:['The menu could not be retrieved. Attach a menu or try again later.','暂时无法获取菜单，可以上传菜单或稍后再试。'],
 SEARCH_LIMIT_REACHED:['This reply has already searched once. Send another message to search again.','这次回复已搜索过一次，请发送新消息再次搜索。'],
 UI_GYM_MISMATCH:['The suggestion does not match the gym you selected. Request it again.','建议与所选健身房不一致，请重新获取。'],
 ACTUAL_MINUTES_REQUIRED:['Tell the assistant how many minutes you actually trained before finishing.','结束前请告诉助手实际训练了多少分钟。'],
 INVALID_ACTUAL_MINUTES:['Enter the actual training time in whole minutes, from 1 to 1,440.','请填写实际训练时长，范围为 1 至 1,440 分钟的整数。'],
 CONDITIONS_CONFIRMATION_REQUIRED:['Clarify the time, gym, equipment or budget you want to change.','请说明要修改的时间、场地、器械状态或预算。'],
 MEAL_TARGET_REQUIRED:['Specify the meal or food you want to change.','请说明要修改哪一餐或哪项食物。'],
 INVALID_MEAL_CHANGES:['Check the portion and nutrition values before saving.','保存前请核对份量和营养数值。'],
 OPERATION_TARGET_REQUIRED:['Choose the saved meal change you want to undo.','请选择要撤销的那次餐食修改。'],
 WORKOUT_TARGET_REQUIRED:['Specify the workout you want to update.','请说明要修改哪次训练。'],
 LOAD_BASIS_REQUIRED:['Specify whether this weight is per hand or the machine’s total load.','请说明这是单手重量还是器械总配重。'],
 LOAD_UNIT_REQUIRED:['State the weight in kilograms.','请说明以公斤为单位的重量。'],
 LOAD_TARGET_REQUIRED:['Specify the exercise and equipment this weight is for.','请说明这个重量对应的动作和器械。'],
 LOAD_CONFIRMATION_AMBIGUOUS:['Confirm one exercise’s weight at a time, with its unit and equipment.','请一次确认一个动作的重量，并注明单位和器械。'],
 LOAD_CONTEXT_REQUIRED:['Choose the workout and equipment before confirming its weight.','确认重量前，请先确定训练与器械。'],
 LOAD_CONTEXT_MISMATCH:['This weight confirmation belongs to an earlier plan. Confirm it for the current exercise.','这次重量确认属于此前方案，请针对当前动作重新确认。'],
 RUN_LEASE_EXPIRED:['The previous reply did not finish. Check saved records before retrying.','此前回复未能完成，请核对已保存记录后重试。'],
 SEARCH_RATE_LIMITED:['Menu search is busy. Attach a menu or try again later.','菜单搜索繁忙，可以上传菜单或稍后再试。'],
 USER_PRIORITY:['The recovery check stopped so your message can be handled first.','恢复检查已停止，将优先处理你的消息。'],
 SOURCE_CONTEXT_MISMATCH:['The records have changed since this message. Check the latest details before sending again.','发送这条消息后记录已有变化，请核对最新信息后再发送。'],
 EXPLICIT_USER_INTENT_REQUIRED:['Please state what you want to record or change.','请说明要记录或修改的内容。'],
 UNDO_CONFLICT:['This meal was changed again. Review its latest details before correcting it.','这餐后来又有修改，请先核对最新记录再调整。'],
 AUTHORIZATION_CONSUMED:['This change has already been processed. Check the latest records.','这次修改已处理，请查看最新记录。'],
 AUTHORIZATION_INVALID:['This change could not be matched to your request. Review the records before trying again.','无法将这次修改与你的请求对应，请核对记录后重试。'],
 CONVERSATION_MISMATCH:['The conversation has changed. Refresh before sending again.','对话已有变化，请刷新后再发送。'],
 INTERNAL_ERROR:['This request could not finish. Check saved records before retrying.','这次请求未能完成，请核对已保存记录后重试。'],
 CONDITIONS_CHANGED:['Today’s conditions have changed. Ask for an updated plan before starting.','今日条件已有变化，请更新方案后再开始。'],
 WORKOUT_REQUIRES_USER_ACTION:['Start or change training progress only when you choose to do so.','请在准备好时主动开始或修改训练进度。'],
 GYM_NOT_FOUND:['Choose one of your saved gyms.','请选择一个已保存的健身房。'],
 EQUIPMENT_OCCUPIED:['This equipment is occupied. Ask to reorder or replace the exercise.','这台器械正被占用，可请助手调整顺序或替换动作。'],
 EQUIPMENT_UNAVAILABLE:['This equipment is unavailable. Ask for a suitable replacement.','此器械不可用，请获取合适的替代动作。'],
 LOAD_CONFIRMATION_REQUIRED:['Confirm a suitable weight before applying this exercise.','请先确认合适的重量，再采用此动作。'],
 INVALID_LOAD:['The suggested weight needs checking. Ask for an updated suggestion.','推荐重量需要核对，请重新获取建议。'],
 WORKOUT_NOT_SCHEDULED:['This workout is not scheduled for today. Check your updated plan.','这场训练不在今日安排中，请查看更新后的计划。'],
 WORKOUT_STATE_CONFLICT:['Training progress has changed. Refresh to continue.','训练进度已有变化，请刷新后继续。'],
 WORKOUT_TIME_EXCEEDED:['This plan exceeds the time available. Ask for a shorter workout.','此方案超出可用时间，请获取更短的训练方案。'],
 EMPTY_WORKOUT:['This plan has no remaining exercises. Ask for an updated plan.','此方案没有待练动作，请重新获取方案。'],
 EXERCISE_TARGET_REQUIRED:['Choose which exercise you mean.','请说明要操作哪个动作。'],
 COMPLETED_EXERCISE_IMMUTABLE:['Completed exercises are kept. Only remaining exercises can change.','已完成动作会保留，只能调整待练动作。'],
 INCOMPLETE_CONFIRMATION_REQUIRED:['Some exercises are unfinished. Confirm if you want to end now.','还有动作未完成，请确认是否现在结束。'],
 REST_CANNOT_START:['Today is a rest day. No workout will be started.','今天安排休息，不会开始训练。'],
 PROPOSAL_ALREADY_APPLIED:['This suggestion is already saved. Continue from your current plan.','此建议已保存，请从当前计划继续。'],
 APPLY_REQUIRES_USER_ACTION:['Use the suggestion’s confirmation button to apply it.','请点击建议下方的确认按钮来应用。'],
 CONTEXT_STALE:['The information behind this suggestion has changed. Ask for an updated plan.','这条建议的依据已变化，请重新获取方案。'],
 CONTEXT_READ_INVALID:['This suggestion could not be verified. Ask for an updated plan.','无法核对这条建议，请重新获取方案。'],
 INVALID_WORKOUT_PROPOSAL:['This workout needs correction before it can be saved. Ask for an updated plan.','此训练方案需要修正后才能保存，请重新获取方案。'],
 INVALID_SCHEDULE:['These dates could not be scheduled. Ask for an updated arrangement.','这些日期暂时无法安排，请重新获取排期。'],
 INVALID_DATE_RANGE:['This date range is unavailable. Choose a different range.','此日期范围不可用，请选择其他范围。'],
 STALE_EPOCH:['This session has changed. Your latest data has been refreshed.','本次会话已有变化，已刷新最新数据。'],
 IDEMPOTENCY_CONFLICT:['This request has changed. Refresh before trying again.','此请求已有变化，请刷新后重试。'],
 SESSION_REQUIRED:['Your session has expired. Refresh to begin again.','会话已过期，请刷新后继续。'],
 INVALID_SESSION:['Your session could not be verified. Refresh to begin again.','无法确认会话，请刷新后继续。'],
 ACTION_NOT_AVAILABLE:['This action is not available yet.','此操作暂不可用。'],
 ATTACHMENTS_NOT_AVAILABLE:['Image upload is not available yet.','图片上传暂不可用。'],
 ORIGIN_NOT_ALLOWED:['This request could not be verified. Reload the app.','无法确认请求来源，请重新打开应用。'],
 UNSUPPORTED_MEDIA_TYPE:['Choose a JPEG, PNG or WebP image.','请选择 JPEG、PNG 或 WebP 图片。'],
 PAYLOAD_TOO_LARGE:['This file or message is too large. Try a smaller one.','文件或消息过大，请缩小后重试。'],
 STORAGE_UNAVAILABLE:['Records are temporarily unavailable. Please try again.','记录暂时无法读取，请重试。'],
 NETWORK_ERROR:['Could not connect. Please try again.','连接失败，请重试。'],
 PROVIDER_ERROR:['The assistant could not finish. Saved changes are kept; check your records before retrying.','助手未能完成回复。已保存的修改会保留，请核对记录后重试。'],
 PROVIDER_NOT_CONFIGURED:['The AI connection is not configured yet. Your records are still available.','AI 连接尚未配置，已有记录仍可查看。'],
 SEARCH_NOT_CONFIGURED:['Menu search is not configured yet. You can attach a menu instead.','菜单搜索尚未配置，可以上传菜单。'],
 VERSION_CONFLICT:['These records have changed. Refresh before trying again.','记录已有变化，请刷新后再试。'],
 STALE_PROPOSAL:['This suggestion is out of date. Ask for an updated plan.','建议已经过期，请重新获取方案。'],
 INVALID_INPUT:['Please check the information and try again.','请检查填写内容后重试。'],
 NOT_FOUND:['This item is no longer available. Refresh your day.','此记录已不可用，请刷新今日数据。'],
 TIMEOUT:['This is taking longer than expected. Check the result before retrying.','处理超时，请先确认结果再重试。'],
 UPLOAD_TOO_LARGE:['Choose an image up to 10 MB.','请选择不超过 10 MB 的图片。'],
 UNSUPPORTED_FILE:['Choose a JPEG, PNG or WebP image.','请选择 JPEG、PNG 或 WebP 图片。'],
 SESSION_RESET:['This session was reset. Your day has been refreshed.','本次会话已重置，今日数据已刷新。'],
 READINESS_UNAVAILABLE:['Readiness is unavailable. Your current plan is still shown.','准备度暂不可用，仍显示当前方案。'],
 START_FAILED:['Your plan was saved, but the workout has not started. Try starting again.','方案已保存，训练尚未开始。请重试开始。'],
 INCOMPLETE_RESPONSE:['The reply was interrupted. Your draft is kept; check saved records before retrying.','回复意外中断，输入已保留；请核对已保存记录后重试。'],
 STREAM_PROTOCOL_ERROR:['The response could not be verified. Refresh before retrying.','无法确认回复所属会话，请刷新后重试。'],
 EMPTY_RESPONSE:['No response was received. Please try again.','未收到回复，请重试。'],
 PREVIEW_ONLY:['This visual preview does not run the AI.','此界面预览未连接 AI。'],
}
const aliases:Record<string,string>={AUTHORIZATION_MISMATCH:'AUTHORIZATION_INVALID',AUTHORIZATION_RUN_MISMATCH:'AUTHORIZATION_INVALID',EQUIPMENT_HAS_NO_LOAD:'INVALID_LOAD',EQUIPMENT_NOT_FOUND:'EQUIPMENT_UNAVAILABLE',INVALID_EQUIPMENT:'EQUIPMENT_UNAVAILABLE',INVALID_EXERCISE_ID:'EXERCISE_TARGET_REQUIRED',OCCUPIED_ORDER_INVALID:'EQUIPMENT_OCCUPIED',METHOD_NOT_ALLOWED:'INVALID_INPUT',ATTACHMENT_TOO_LARGE:'UPLOAD_TOO_LARGE',UNSUPPORTED_ATTACHMENT_FORMAT:'UNSUPPORTED_FILE',ATTACHMENT_STORAGE_INVALID:'STORAGE_UNAVAILABLE',CONTEXT_READ_REQUIRED:'CONTEXT_READ_INVALID',INVALID_MODEL_OUTPUT:'PROVIDER_ERROR',MEAL_REQUIRES_USER_ACTION:'EXPLICIT_USER_INTENT_REQUIRED',USER_INTENT_REQUIRED:'EXPLICIT_USER_INTENT_REQUIRED',PROPOSAL_REQUIRES_USER_ACTION:'EXPLICIT_USER_INTENT_REQUIRED',RUN_NOT_ACTIVE:'RUN_STOPPED',SEARCH_ABORTED:'RUN_STOPPED',SEARCH_CONFIGURATION_INVALID:'SEARCH_NOT_CONFIGURED',SEARCH_INVALID_RESPONSE:'SEARCH_FAILED',SEARCH_RESPONSE_TOO_LARGE:'SEARCH_FAILED',TOOL_LIMIT_EXCEEDED:'PROVIDER_ERROR',USE_CHAT_READINESS_CHECK:'ACTION_NOT_AVAILABLE'}
export function errorText(code:string,locale:Locale){return (errors[aliases[code]||code]||errors.PROVIDER_ERROR)[locale==='en'?0:1]}
